### ISSUE TITLE
Phase I polishing

### ISSUE THREAD

**Issue by nsheff** [databio/bedhost#11]
# Phase 1 polishing

These are the things I've found that I think we should polish up to finalize phase I before moving on to phase 2.

## Display cleanup
- [x] png images displayed on the splash page should be links to bigger images (PDFs)
- [x] include links to download the bed file, and to JSON metadata, on the splash page for the BED file
- [x] add a digest (md5 checksum for the bed file) to the splash page
- [x] The PNG titles should be below, not next to the plots
- [x] The display size of the PNG thumbnails should be reduced to about 75% of current size
- [x] Splash page should show the name of the BED file
- [x] Needs a logo (logo is broken)
- [x] The splash page should show the other metadata associated with the file, like cell type. this information is included in the LOLA database format, for example, and should therefore be passed on as PEP csv columns. All this information needs to be displayed on the splash page.

## Features
- [x] there should be some way to locate files on the main page; like a search bar. several search components are outlined in phase I, such as searching by regions, cpg content, etc. these should have corresponding boxes on the dashboard to retrieve lists of bed file links.
- [x] implement all requested API endpoints in phase I document

## Repo cleanup
- [x] Add BSD2 license files
- [ ] rename `bedstat-rest-api` to `bedbase`.

## Bedstat cleanup
- [x] bedstat should NOT produce a 'file.path' file, but should record the path in the json document. Furthermore, the path should be stored as a RELATIVE path, not an absolute path. the PEP and files should be able to be moved around easily.
- [x] plot text is too small; should use smaller canvas size (not resolution) for PNGs (using width=x, height=x in the R `png()` and `pdf()` function calls, I think).
- [x] the pipeline should produce both PNGs (for thumbnails) and PDFs (vector, as the target of the links).
- [x] bedstat is currently keeping files unzipped. The specification calls for files to be stored and served in compressed format.
